ProductPackagesUI/Controllers/PackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BusinessLayer;
using BusinessLayer.Managers.Currency;
using BusinessLayer.Managers.Product;
using BusinessLayer.Managers.ProductPackage;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using ProductPackagesUI.Helpers;
using ProductPackagesUI.Models;

namespace ProductPackagesUI.Controllers
{
    public class PackagesController : Controller
    {
        private readonly IProcessWebRequest _processWebRequest;
        private readonly ICurrencyManager _currencyManager;
        private readonly IProductPackageManager _productPackageManager;
        private readonly IProductManager _productManager;
        private readonly IServiceProvider _serviceProvider;
        private readonly IControllerHelper _controllerHelper;
        private readonly IConfiguration _configuration;
        
        public PackagesController(
            IConfiguration configuration,
            IServiceProvider serviceProvider,
            IProcessWebRequest processWebRequest,
            ICurrencyManager currencyManager,
            IProductPackageManager productPackageManager,
            IProductManager productManager,
            IControllerHelper controllerHelper)
        {
            _configuration = configuration;
            _controllerHelper = controllerHelper;
            _serviceProvider = serviceProvider;
            _productPackageManager = productPackageManager;
            _processWebRequest = processWebRequest;
            _currencyManager = currencyManager;
            _productManager = productManager;
        }

        #region Index

        public IActionResult Index(string currency = null)
        {
            _controllerHelper.ConfigureCurrencyInViewBag(ViewBag, currency);
            var viewModel = new ProductPackageIndexViewModel();

            var productPackages = _productPackageManager.GetAllProductPackages(currency);
            viewModel.ProductPackageViewModels = productPackages.Select(productPackage => new ProductPackageViewModel(productPackage)).ToList();

            return View(viewModel);
        }

        #endregion

        #region Details

        public IActionResult Details(string id, string currency = null)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index", new { currency });
            }
            _controllerHelper.ConfigureCurrencyInViewBag(ViewBag, currency);
            var productPackage = _productPackageManager.GetProductPackage(id, currency);
            var viewModel = new ProductPackageDetailsViewModel();
            viewModel.ProductPackageViewModel = new ProductPackageViewModel(productPackage);

            foreach (var product in viewModel.ProductPackageViewModel.Products)
            {
                var productModel = _productManager.GetProductModel(product.Id);
                product.Name = productModel.Name;
                product.Value = _currencyManager.ApplyExchangeRate(productModel.usdPrice, currency);
            }
            return View(viewModel);
        }

        #endregion

        #region Delete
        
        [HttpGet]
        public IActionResult ConfirmDelete(string id, string currency = null)
        {
            var productPackage = _productPackageManager.GetProductPackage(id, currency);
            _controllerHelper.ConfigureCurrencyInViewBag(ViewBag, currency);
            var viewModel = new ProductPackageDetailsViewModel();
            viewModel.ProductPackageViewModel = new ProductPackageViewModel(productPackage);
            return PartialView("_ConfirmDelete", viewModel);
        }

        [HttpPost]
        public IActionResult ConfirmDelete(ProductPackageDetailsViewModel productPackage, string currency = null)
        {
            _productPackageManager.DeleteProductPackage(productPackage.ProductPackageViewModel._id);
            return RedirectToAction("Index", new { currency });
        }

        #endregion

        #region Create

        [HttpGet]
        public IActionResult Create(string currency = null)
        {
            _controllerHelper.ConfigureCurrencyInViewBag(ViewBag, currency);
            var viewModel = new EditProductPackageViewModel();
            var productModels = _productManager.GetProductModels();

            foreach(var product in productModels)
            {   
                var productViewModel= new ProductViewModel(product);
                productViewModel.Value = _currencyManager.ApplyExchangeRate(product.usdPrice, currency);            
                viewModel.AvailableProducts.Add(productViewModel);
            }
            
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Create(EditProductPackageViewModel viewModel, string currency = null)
        {
            if (!ModelState.IsValid)
            {
                _controllerHelper.ConfigureCurrencyInViewBag(ViewBag, currency);
                return View(viewModel);
            }
            var data = new ProductPackageModel()
            {
                Name = viewModel.Name,
                Description = viewModel.Description,
                Products = new List<ProductModel>()
            };


            if (viewModel.SelectedProductsIds != null && viewModel.SelectedProductsIds.Any())
            {
                foreach (var productIds in viewModel.SelectedProductsIds)
                {
                    data.Products.Add(new ProductModel() { Id = productIds });
                }
            }

            var result = _productPackageManager.CreateProductPackage(data);

            return RedirectToAction("details", new { id = result._id, currency });
        }

        #endregion

        #region Edit

        [HttpGet]
        public IActionResult Edit(string id, string currency=null)
        {
            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }
            
            var productPackage = _productPackageManager.GetProductPackage(id);

            var viewModel = new EditProductPackageViewModel();
            viewModel.Name = productPackage.Name;
            viewModel.Description = productPackage.Description;
            viewModel.SelectedProductsIds = productPackage.Products.Select(p => p.Id).ToList();

            SetupEditView(viewModel, ViewBag, currency);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(string id, EditProductPackageViewModel viewModel, string currency = null)
        {
            if (!ModelState.IsValid)
            {
                SetupEditView(viewModel, ViewBag, currency);
                return View(viewModel);
            }

            if (string.IsNullOrEmpty(id))
            {
                return RedirectToAction("Index");
            }

            var data = new ProductPackageModel()
            {
                _id = id,
                Name = viewModel.Name,
                Description = viewModel.Description,
                Products = new List<ProductModel>()
            };

            if (viewModel.SelectedProductsIds != null && viewModel.SelectedProductsIds.Any()) {
                foreach (var productIds in viewModel.SelectedProductsIds)
                {
                    data.Products.Add(new ProductModel() { Id = productIds });
                }
            }
            _productPackageManager.UpdateProductPackage(data);
            return RedirectToAction("details", new { id, currency });
        }

        private void SetupEditView(EditProductPackageViewModel viewModel, dynamic viewBag, string currency)
        {
            _controllerHelper.ConfigureCurrencyInViewBag(ViewBag, currency);

            var productModels = _productManager.GetProductModels();

            foreach (var product in productModels)
            {
                var productViewModel = new ProductViewModel(product);
                productViewModel.Value = _currencyManager.ApplyExchangeRate(product.usdPrice, currency);
                viewModel.AvailableProducts.Add(productViewModel);
            }
        }
        #endregion
    }
}

ProductPackagesUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Product Packages</title>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Product Packages", "Index", "Packages", new { currency = ViewBag.CurrentCurrency }, new {@class="navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Packages", "Index", "Packages", new { currency = ViewBag.CurrentCurrency })
                    </li>
                    <li>
                        @Html.ActionLink("Contact", "Contact", "Home", new { currency = ViewBag.CurrentCurrency })
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Currency: <span id="currencyTag">@ViewBag.CurrentCurrency (@ViewBag.CurrencySymbol)</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            @foreach (var currencyType in ViewBag.AvailableCurrency)
                            {
                                <li><a onclick="updateCurrency('@currencyType')">@currencyType</a></li>
                            }
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="navbar-collapse collapse">
            </div>

        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ProductPackagesUI</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        function updateCurrency(currency) {
            window.location.href = "?currency=" + currency;
        }
    </script>
    @RenderSection("Scripts", required: false)

</body>
</html>